### ISSUE TITLE
How to install it in OH3

### ISSUE THREAD

**Issue by misko903** [seaside1/omatic#1]
Hello,
this addon is exactly what I am looking for. The only thing is, I don't know how to install it. Could you provide a bit of **documentation** how to do it?

Thanks,
Michal

**Comment by seaside1** [comment]
I've readded the installation instuctions.

**Comment by misko903** [comment]
Thanks for installation instructions. Really great addon! I have tested it recently on my Tasmota Smart Socket with soldering machine connected. Notifications to my OpenHAB android app works like a charm!
RPi4B, OpenHABian3.
You should force the devs to add the binding to the OH repository. **It is really what needs to be there!!!**

Greets from Slovakia 😃
