### ISSUE TITLE
Reccomendation for descritptions

### ISSUE THREAD

**Issue by misko903** [seaside1/omatic#2]
Maybe one recommendation - better description of thing configuration in OH. I understad it, but it will be better to understand it at first glance.

**Energy Input Item** - is it ok to input ENERGYToday?
For example: **Active Threshold** - which units are used - [W] or [kW] or [%]
**Timer Delay** - [sec] ?
practically like you have it in **Static Power (W) **

Thanks and again, many thanks for such a practical addon!

**Comment by seaside1** [comment]
Thank you for the feedback, I updated the table with energy units.
