### ISSUE TITLE
Support Numbers with dimensions

### ISSUE THREAD

**Issue by hman-78** [seaside1/omatic#3]
I found an issue regarding numbers with dimensions. It would be great if the "Power Input Item" could also support things with dimensions like items of type Number:Power.

My workaround was to change the type of Item providing the information about the power consumption from Number:Power to Number.

Thanks for this great plugin!

**Comment by seaside1** [comment]
Hi!

Thank you for your report. I will take a look at it, I haven't added that type of items myself.

**Comment by seaside1** [comment]
Added support for Number:Power and Number:Energy
