### ISSUE TITLE
EnergyInputItem not working with Number:Energy quantity type

### ISSUE THREAD

**Issue by mwildbolz** [seaside1/omatic#4]
Hi!

Thanks a lot for this great binding - works like a charm.
Only thing I discovered is, that the EnergyInputItem is not recognized, if it is of type Number:Energy.
Seems like this type is missing in the ENERGY_ITEM_TYPES Set https://github.com/seaside1/omatic/blob/e8e14d2584bb11876a93f27fa3e27e5e967de34f/src/main/java/org/openhab/binding/omatic/internal/handler/OMaticMachineThingHandler.java#L82

Maybe you could check/correct this?

Thanks...

**Comment by seaside1** [comment]
Hi! Thanks will have a look. Should be easy to fix.

**Comment by seaside1** [comment]
Hopefully fixed with the beta1 release. Please reopen if it is still an issue.
