### ISSUE TITLE
Frequently state updates on EventBus neccessary?

### ISSUE THREAD

**Issue by mwildbolz** [seaside1/omatic#6]
I just saw, that there are very frequent updates of all items on the EventBus (approx. every 3-4s) - ItemStateEvent without a change.
Is this really necessary?

These are just state updates, no new values. And the statemachine is currently not running.
On my opinion, this is not neccessary and just generates traffic on the EventBus.

**Comment by seaside1** [comment]
This sounds strange. As far as I know this addon does not update any items unless it is running, the Items will be updated if they are linked to a channel that is updated. 

Do you have any more info you can provide on this?

Examples of what items and how they are linked to the channels of omatic.
