### ISSUE TITLE
Example file .things configuration with all params

### ISSUE THREAD

**Issue by axi92** [seaside1/omatic#7]
Is there a list of params for the file things configuration?
I dont want do do it via the UI.

**Comment by seaside1** [comment]
Yes you can look at the documentation of the thing config https://github.com/seaside1/omatic#thing-configuration
I have not done this myself. If you manage to get it working, you could submit your thing config and I can update the example documentation with a file based example as well.

**Comment by axi92** [comment]
I just checked the code it is using the same names as here:
https://github.com/seaside1/omatic/blob/master/src/main/java/org/openhab/binding/omatic/internal/OMaticMachineThingConfig.java#L28-L36

**Comment by bananajoe86** [comment]
Thing omatic:machine:e74a54e7  [ 
        
          
    name = "WHATYOUWANT",
    powerInputItem = "POWERITEM",
    activeThreshold = 10,
    idleTime = 60,
    cost = 0.35,
    dateFormat = "YYYY-MM-dd HH:mm:ss"]

**Comment by axi92** [comment]
Sry for the late reply that is my .things file:

```
Thing omatic:machine:statewashingmachine "Statemachine Washingmachine" [ name="statemachine_Washingmachine", powerInputItem="washerpower", energyInputItem="washerenergy", cost=0.50 ]
Thing omatic:machine:statepc "Statemachine PC" [ name="statemachine_PC", powerInputItem="pcpower", energyInputItem="pcenergy", cost=0.50 ]
Thing omatic:machine:statedishwasher "Statemachine Dishwasher" [ name="statemachine_dishwasher", powerInputItem="dishwasherpower", energyInputItem="dishwasherenergy", cost=0.50 ]
Thing omatic:machine:statefridge "Statemachine Fridge" [ name="statemachine_fridge", powerInputItem="fridgepower", energyInputItem="fridgeenergy", cost=0.50 ]
```
